### ISSUE TITLE
the text "Posts" on the index(home) pages  

### ISSUE THREAD

**Issue by ICTime** [jekylltools/jekyll-ideal-image-slider-include#8]
On the index (home) page,  the is a "Post"  words above the blog entry. 
where does this from the template?  I grep the the dir, but can't find it when I am trying to modify it.

Second question 
Does this the jekyll ideal image slider support Category/tags like the legacy Jekyll ? 

<ul class="tag_box inline">
  {% assign categories_list = site.categories %}
  {% include JB/categories_list %}
</ul>
{% for category in site.categories %}

Sorry to ask these question, I really like this template, want to use it to replace my old Jekyll.

**Comment by jekylltools** [comment]
So `jekyll-ideal-image-slider-include` is just an [include](https://jekyllrb.com/docs/includes/) to use in your own Jekyll site. It is not an entire theme. The [master branch](https://github.com/jekylltools/jekyll-ideal-image-slider-include/tree/master) contains just the code for the include. The [gh-pages branch](https://github.com/jekylltools/jekyll-ideal-image-slider-include/tree/gh-pages) contains the code for the [demonstration site](https://jekylltools.github.io/jekyll-ideal-image-slider-include/about/). On the demo site I use the default Jekyll theme which is the [minima theme](https://github.com/jekyll/minima). I'm just using that theme to demonstrate how the Ideal Image Slider works. So if you want to use the minima theme for your own site, you can fork the [minima theme](https://github.com/jekyll/minima) and then add the `jekyll-ideal-image-slider-include` to it yourself.

To answer your question, `Posts` appears on the home page because it is inside the `home.html` template in the minima theme. It is on [Line 7 in `home.html`](https://github.com/jekyll/minima/blob/cd8c3e0ebad408fe54e1129031a463ae933d3520/_layouts/home.html#L7)

And `jekyll-ideal-image-slider-include` does not support tags/categories because those only apply to Jekyll posts, pages and collections. The minima theme does support tags/categories.

I'm unable to provide further support for the minima theme here, from now on please ask theme related questions on the minima repository. Thanks!
